# Generated by Django 3.0 on 2020-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_listitem_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
